module.exports = {
  apps: [
    {
      name: "argochain_explorer_backend",
      script: "node",
      args: "src/index.js",
      instances: 1,
      autorestart: true,
      time: true,
      restart_delay: 3000,
      watch: true,
      ignore_watch : ["node_modules", "logs", "src/public"],
      max_memory_restart: "1G",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      node_args: '--max-old-space-size=2048',
      exec_mode: 'cluster',
      error_file: './logs/argochain_explorer_backend-error.log',
      out_file: './logs/argochain_explorer_backend-out.log',
      combine_logs: true,
      env: {
        NODE_ENV: 'development',
        POSTGRES_DB: process.env.POSTGRES_DB,
        POSTGRES_USER: process.env.POSTGRES_USER,
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
        DATABASE_URL: process.env.DATABASE_URL,
        ARGOCHAIN_RPC_URL: process.env.ARGOCHAIN_RPC_URL,
        FETCHING_BATCH_SIZE: process.env.FETCHING_BATCH_SIZE,
      },
      env_production: {
        NODE_ENV: 'production',
        POSTGRES_DB: process.env.POSTGRES_DB,
        POSTGRES_USER: process.env.POSTGRES_USER,
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
        DATABASE_URL: process.env.DATABASE_URL,
        ARGOCHAIN_RPC_URL: process.env.ARGOCHAIN_RPC_URL,
        FETCHING_BATCH_SIZE: process.env.FETCHING_BATCH_SIZE,
      }
    },
  ],
};
