/**
 * Strips metadata from bytecode to enable comparison
 * @param {string} bytecode - The bytecode to strip metadata from
 * @returns {string} - The bytecode without metadata
 */
function stripMetadata(bytecode) {
    if (!bytecode || typeof bytecode !== 'string') {
        return '';
    }
    
    if (bytecode.startsWith('0x')) {
        bytecode = bytecode.slice(2);
    }
    
    // Remove metadata that starts with either "a2646970667358" or "fea2646970667358"
    // This handles both the metadata hash and the CBOR-encoded metadata
    const metadataRegex = /(?:fe)?a2646970667358[0-9a-f]*$/i;
    return bytecode.replace(metadataRegex, '');
}

/**
 * Compares two bytecodes after stripping metadata
 * @param {string} generatedBytecode - The locally generated bytecode
 * @param {string} deployedBytecode - The on-chain deployed bytecode
 * @returns {Object} - Comparison result with stripped bytecodes
 */
function matchContractBytecode(generatedBytecode, deployedBytecode) {
    const strippedGeneratedBytecode = stripMetadata(generatedBytecode);
    const strippedDeployedBytecode = stripMetadata(deployedBytecode);
    
    return {
        isMatch: strippedGeneratedBytecode === strippedDeployedBytecode,
        strippedGeneratedBytecode,
        strippedDeployedBytecode,
        generatedLength: strippedGeneratedBytecode.length,
        deployedLength: strippedDeployedBytecode.length
    };
}

/**
 * Extracts metadata from bytecode for debugging
 * @param {string} bytecode - The bytecode to extract metadata from
 * @returns {Object} - Metadata information
 */
function extractMetadata(bytecode) {
    if (!bytecode || typeof bytecode !== 'string') {
        return { hasMetadata: false, metadata: null };
    }
    
    if (bytecode.startsWith('0x')) {
        bytecode = bytecode.slice(2);
    }
    
    const metadataRegex = /(?:fe)?a2646970667358([0-9a-f]*)$/i;
    const match = bytecode.match(metadataRegex);
    
    if (match) {
        return {
            hasMetadata: true,
            metadata: match[0],
            metadataHash: match[1] || null
        };
    }
    
    return { hasMetadata: false, metadata: null };
}

module.exports = { stripMetadata, matchContractBytecode, extractMetadata };
